<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Naruto</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link rel="stylesheet" href="css/styles.css">
</head>
<body>
<!-- header content -->
    <header>
        <h1>Naruto</h1>
    </header>
<!-- navigation content -->
    <nav>
        <ul>
            <li><a href="index.html">Home</a></li>
            <li><a href="details.html">Details</a></li>
            <li><a href="about.html">About</a></li>
            <li><a href="new-character-form.html">Add a Character</a></li>
        </ul>

    </nav>
<!-- main body content -->
    <main>
        <img src="images/group.jpg" alt="">
        <h1>About Naruto</h1>
        <p>Learn more about the Naruto universe</p>

        <h2>Welcome to the Naruto Character Gallery</h2>
        <p>Naruto is a Japanese anime and manga series that follows Naruto Uzamaki. He is a young ninja with the dream of one day becoming Hokage, the leader of his village. Born with a great source of power inside of him, Naruto is an outcast in his village but is determined to gain the respect of his fellow peers and community. We follow Naruto across its multiple arcs, <i>Part 1</i>, <i>Shippuden</i>, <i>Boruto</i>. The story explores themes such as loneliness, identity, and perseverance.  </p>

        <h2>More Details</h2>
        <p>This gallery is dedicated to all characters of naruto. You will be able to find characters from  every arc and even filler stories, so be on the lookout for characters you might not expect!</p>
    </main>
<!-- footer information -->
    <footer>
        @copy; 2026 Naruto Character Gallery. Made for school assignment
    </footer>

    
</body>
</html>

