<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Naruto</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link rel="stylesheet" href="css/styles.css">
</head>
<body>
<!-- header content -->
    <header>
        <h1>${Character.name}</h1>
    </header>
<!-- navigation content -->
    <nav>
        <ul>
            <li><a href="index.html">Home</a></li>
            <li><a href="details.html">Details</a></li>
            <li><a href="about.html">About</a></li>
            <li><a href="new-character-form.html">Add a Character</a></li>
        </ul>

    </nav>
<!-- main body content -->
    <main>
       <img src="images/naruto.jpg" class="details-img" alt="Teenage Naruto Uzamaki in sage mode">
       <div class="section-title">
            <h3>Backstory</h3>
            <p>Naruto Uzamaki grew up as an orphan in the Hidden Leaf Village. He was born with the power of the Nine-Tail Fox sealed inside him. As a result of this, Naruto was shunned by his village but his community. Despite this, he developed an unbreakable determination to be acknowledged and to one day become Hokage. </p>
       </div>

       <div class="section-title"></div>
        <h3>First Appearance</h3>
        <p>Naruto first appears in <em>Naruto</em> episode 1 of the anime (2002).</p>

        <div class="section-title">
            <h3>Personality Trait</h3>
            <p>Naruto is energetic, stubborn, loyal and optimistic. He never gives up on his goals or friends, and his compassion often changed the hearts of those around him.</p>
        </div>
    </main>
<!-- footer information -->
    <footer>
        @copy; 2026 Naruto Character Gallery. Made for school assignment
    </footer>

    
</body>
</html>