<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Naruto</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link rel="stylesheet" href="css/styles.css">
</head>
<body>
<!-- header content -->
    <header>
        <h1>Naruto</h1>
    </header>
<!-- navigation content -->
    <nav>
        <ul>
            <li><a href="index.html">Home</a></li>
            <li><a href="details.html">Details</a></li>
            <li><a href="about.html">About</a></li>
            <li><a href="new-character-form.html">Add a Character</a></li>
        </ul>

    </nav>
<!-- main body content -->
    <main>
        <div class="search-container">
            <input type="text" placeholder="Search character">
        </div>

        <div class="card-grid">
            <div class="character-card">
                <img src="images/naruto.jpg" class="image-character" alt="">
                <h3>Naruto Uzamaki</h3>
                <p>A determined ninja who dreams of becoming hokage. Known for his determination and powerful chakra.</p>
                <a href="details.html" class="details-btn">More Details</a>
            </div>

            <div class="character-card">
                <img src="images/kaksashi.jpg" class="image-character" alt="">
                <h3>Kakashi Hatake</h3>
                <p>A skilled jonin, known for his Sharingan and experienced leadership. Sensei of Team 7</p>
                <a href="details.html" class="details-btn">More Details</a>
            </div>

            <div class="character-card">
                <img src="images/killer-bee.jpg" class="image-character" alt="">
                <h3>Killer Bee</h3>
                <p>The jinchuriki of the 8-tails. A master swordsman and rapper with immense power</p>
                <a href="details.html" class="details-btn">More Details</a>
            </div>

            <div class="character-card">
                <img src="images/madara.jpg" class="image-character" alt="">
                <h3>Madara Uchiha</h3>
                <p>A legendary Uchiha with incredible power. Co-founder of the Hidden Leaf village</p>
                <a href="details.html" class="details-btn">More Details</a>
            </div>

            <div class="character-card">
                <img src="images/pain.jpg" class="image-character" alt="" >
                <h3>Pain</h3>
                <p>Leader of the Akatsuki. Believes that true peace can only be obtained through suffering</p>
                <a href="details.html" class="details-btn">More Details</a>
            </div>
        </div>

    </main>
<!-- footer information -->
    <footer>
        @copy; 2026 Naruto Character Gallery. Made for school assignment
    </footer>

    
</body>
</html>