<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Naruto</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link rel="stylesheet" href="css/styles.css">
</head>
<body>
<!-- header content -->
    <header>
        <h1>Naruto</h1>
    </header>
<!-- navigation content -->
    <nav>
        <ul>
            <li><a href="index.html">Home</a></li>
            <li><a href="details.html">Details</a></li>
            <li><a href="about.html">About</a></li>
            <li><a href="new-character-form.html">Add a Character</a></li>
        </ul>
    </nav>
<!-- main body content -->
    <main>
        <form action="">
            <h2>Character Information</h2>
            <!-- Name of character -->
            <label for="name">Character Name</label>
            <input type="text" id="name" name="name" placeholder="ex. Naruto Uzamaki">

            <!-- Universe of character -->
            <label for="timeline">Timeline</label>
            <select name="timeline" id="timeline">
                <option value="part1">Part 1</option>
                <option value="shippuden">Shippuden</option>
                <option value="boruto">Boruto</option>
            </select>

            <!-- Character role -->
            <label for="role">Role</label>
            <select name="role" id="role">
                <option value="hero">Hero</option>
                <option value="villian">Villian</option>
                <option value="other">Other</option>
            </select>

            <!-- image URL -->
            <label for="image">Image URL</label>
            <input type="text" id="image" name="image" placeholder="www.example.com/character.jpg">

            <!-- short description -->
            <label for="description">Short Description</label>
            <textarea name="description" id="description" placeholder="Write a short 1-2 sentence description about the character"></textarea>

            <button type="submit">Submit</button>
        </form>
    </main>
<!-- footer information -->
    <footer>
        @copy; 2026 Naruto Character Gallery. Made for school assignment
    </footer>

    
</body>
</html>